language: node_js
node_js:
- "node"
os: linux
env:
  global:
  - secure: DvboTqshlRyorzFQRAV12e2JeigRwZvEjmE4n5Hg1NZDnpQlByuETU8oJtHtIp8gy0zBurK+qwD94CyJQS7LoJbY+VLC1RItjmQE0J8/LLF8GUxdzRdjBjrJT6rqFCdmtT8oQyF+ogfOtOwC0L+0o8RbgDYZhqRkqB4oYHz3U2GTjPOGiI/Ny1ZvfXOecMAA7aU8XAP6GxYIMlswPBWazqLhYl7pd9gn39P/xn98cnEiiRDzzs4swIqidqtmxJIz65TImJ5/Fed7MqBYHPxcCvS4d2QF+TSsl1GFnIsY5sbeFqz+pHFA0WgZaJbN57IFoE0g/53LiCUkeBVlnf+8cz8PVbjmGbUeGJPA7qQcw0nNZiR/yx93jEjgweR/Ps3KzM5WyECD6Wy/EmLnqHPpWiLVy+KUszM+rV7g+G6x5MTkrV5LYeKPfwlne/MGyHLMt1EXHQnEd7dQWngAjxdRiOeES/mM7dfToHV5k03KqF6wViY9PXDcveTgWFohZD7g2rklLhfsuQNeb1IQQ+I+ABIqUSlLhACMgxoHX8lyHx+d2Vhwf1pBBB6SnpcpvqCQuqJR7oU/X26DHZWb8cvQzjb+B1Ex0fgoMUZIysB/BV6qZ+4mfJJgd74psD0QUwR0+Yk2nQiz7V81axdcFbGh0/u2+snaezT+CmorXqnDjrI=
  - secure: vk6oXDg7cw3O8Ffudo7Nz/6KK5oOBHtllvAqgjVXl7qGX1r2f18GWGkNOhyCHUjsO4jwBlWcmFMlOBegSi668/7J1yMrqm+1iSia86IyHPI2G3KF4kRbMQDyFNjgEI/KCHwKeHw1mpmg74Tyk5Q4B+M/ZbC7FVO5hpDiTLvbSAhhnq0YSi09fyHYV57PlXm70aIfXu6Wcoxv92PofRbBl406HrpyOREbywa1I+p7kur9HQtgleu9j2aW0xR1409ZQxp8qPUlDCeO6X/wo6deVYkMolSWBh9rVf56vBcOb5rqI/RFKvVIo3c2g61b1vpt2NhQuoYX+whRW+xw+XKUwileclBU86rYkBUn2FLr8NiBn1CfYyYONuEYP+ig2bySzbmbRewsPecxGFnxXuy5YXH9tHFBDr5f3/TXJ6qvaspxZxZ/JY6Z5V+fTeY/krKfPnKl/A7nJFpx8rvWMkiGWVXobQ9dxICQJW6ny+NATWSu+KVH5x3IbtksQiJbPvcnIgET+4o7MqDNsL4l0j/hLNtA+AtIWxzYdhcmrN1YXXR5BxirOrOlWQepxIbrx8Zw7yzPnrChd/3nvfdO2k0v+9iqqJXaZXG2grqJDe0dJRvrNNFHponjXMccaShwnw7xYQV/2mQtdC55IBGIKriI15sxZ8x5ikNNFJK4Z1WG/Wc=

install:
- npm i @cloudflare/wrangler -g

script:
- true

deploy:
- provider: script
  script: wrangler publish --env ci
  skip_cleanup: true
  on:
    all_branches: true

- provider: script
  script:
    wrangler publish --env staging
  skip_cleanup: true
  on:
    branch: staging

- provider: script
  script: wrangler publish --env production
  skip_cleanup: true
  on:
    branch: master
